### PR TITLE
Added fallback for `__class` to `class` for BC

### PR DESCRIPTION
**Pull request by klimov-paul**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | BC with old Yii notation

### CODE REVIEW

**Comment by samdark** [comment]
I don't think we need it. It is very likely that a property named `class` will be in the class. That's common for patterns like single table inheritance.

**Comment by klimov-paul** [comment]
> It is very likely that a property named class will be in the class.

Such ability remains, see the unit tests.

> Since we have a BC-breaking release, we have a chance not to introduce features deprecated right from the first version.

I do not like repeating old mistake of Yii1 -> Yii2 migration. I would like to keep as much BC as possible at the initial major release.

**Comment by klimov-paul** [comment]
If accepted, such fallback should be removed somewhere around version 1.0.2 or 1.0.3.

**Comment by schmunk42** [comment]
I'd not include it, to me it adds more confusion. 

I also find it much harder to deprecate it in a future version, ie. if you have 3rd party libs who don't have this fixed they'll work for 1.0.0 and 1.0.1 and people will stay on those, because they can't update their apps.

**Comment by klimov-paul** [comment]
Fallback should be considered while intergating with `yiisoft/yii` package. If there will be such way - it should be considered there. This package should not have such fallabck.
See:
https://github.com/yiisoft/yii2/issues/15436

**Pull request closed without merging**
